INSERT INTO challenges (card_name, card_strength, image_url_key, narrative, bonus_ryo)
VALUES 
('Giải cứu thầy Iruka', 20, 'cuu_iruka', 'Naruto đánh bại Mizuki và học được Bí mật về Cửu Vĩ, bắt đầu hành trình trở thành ninja.', 5000),
('Gặp gỡ thành viên đội 7 Sakura', 60, 'gap_Sakura', 'Naruto thích Sakura ngay từ cái nhìn đầu tiên.', 6000),
('Gặp gỡ thành viên đội 7 Sasuke', 80, 'gap_Sasuke', 'Cool ngầu, học giỏi, đúng hình tượng con nhà người ta.', 7000),
('Bài kiểm tra lấy chuông', 100, 'lay_chuong', 'Đội 7 hợp tác vượt qua bài kiểm tra chuông của Kakashi, học được bài học về tinh thần đồng đội.', 8000),
('Chiến đấu với Zabuza', 120, 'vs_yabuza', 'Đội 7 đối đầu Zabuza để bảo vệ Tazuna, lần đầu trải nghiệm chiến đấu thực sự và sát khí của một ninja.', 9000),
('Kì thi chunin', 150, 'thi_chunin', 'Naruto đánh bại Gaara đang hóa thành Shukaku, giúp Gaara nhận ra sức mạnh của tình bạn và chấm dứt cuộc xâm lăng làng Lá.', 10000),
('Gặp gỡ Jiraiya', 180, 'gap_jiraiya', 'Naruto bị Jiraiya đánh bại dễ dàng khi trêu chọc, mở đầu mối quan hệ thầy trò quan trọng giữa hai người.', 20000),
('Sasuke bỏ làng', 200, 'sasuke_bo_lang', 'Sasuke rời làng để theo Orochimaru nhằm tìm sức mạnh báo thù Itachi, bỏ lại tình bạn và lý tưởng cũ.', 30000),
('Giải cứu Gaara 1', 230, 'giai_cuu_gaara', 'Gaara chiến đấu quyết liệt với Deidara để bảo vệ làng Cát nhưng bị bắt đi, mở đầu cuộc truy đuổi của liên minh làng Lá.', 40000),
('Giải cứu Gaara 2', 260, 'sakura_vs_sasori', 'Sakura phối hợp cùng Chiyo đánh bại Sasori trong trận đấu căng thẳng, chứng minh sự trưởng thành và sức mạnh mới của cô.', 50000),
('Thành viên mới đội 7', 300, 'doi7_moi', 'Sai gia nhập Đội 7 thay thế Sasuke, ban đầu lạnh lùng khó gần nhưng dần học được ý nghĩa của tình bạn.', 60000),
('Gặp lại Sasuke', 310, 'gaplai_sasuke', 'Naruto và Sasuke chạm trán tại căn cứ Orochimaru, bộc lộ lập trường trái ngược nhưng chưa thể đưa Sasuke về.', 70000),
('Đối đầu Akatsuki 1', 320, 'asuma_vs_hidan', 'Asuma đối đầu Hidan và Kakuzu để ngăn Akatsuki, nhưng bị Hidan giết, để lại cú sốc lớn cho học trò.', 80000),
('Đối đầu Akatsuki 2', 330, 'dung_do_kakuzu', 'Kakashi phối hợp với Naruto đánh bại Kakuzu, đánh dấu lần đầu Naruto sử dụng thành công tuyệt kỹ Rasenshuriken.', 90000),
('Đối đầu Akatsuki 3', 340, 'jiraiya_vs_pain', 'Jiraiya xâm nhập Làng Mưa để điều tra Akatsuki, hy sinh sau trận chiến ác liệt với Pain và gửi lại mật mã quan trọng cho làng Lá.', 100000),
('Sasuke báo thù', 350, 'sasuke_bao_thu', 'Sasuke quyết chiến với Itachi và giành chiến thắng, nhưng sau đó phát hiện sự thật đau lòng về quá khứ của anh trai mình.', 150000),
('Pain tấn công làng lá', 360, 'naruto_vs_pain', 'Naruto đánh bại Pain trong trận chiến tàn khốc bảo vệ làng Lá và cảm hóa Nagato, giúp anh hy sinh để hồi sinh mọi người.', 200000),
('Đối đầu Akatsuki 4', 370, 'kisame_vs_bee', 'Killer Bee chiến đấu với Kisame để bảo vệ tự do của mình, cuối cùng đánh bại hắn nhờ phối hợp với Bát vĩ và sự linh hoạt tuyệt vời.', 250000),
('Akatsuki nội chiến', 380, 'oboto_vs_konan', 'Konan quyết liệt chống lại Tobi để bảo vệ di sản của Nagato, nhưng bị hắn giết sau trận chiến dữ dội.', 300000),
('Đại chiến ninja 1', 400, 'zetsu', 'Liên minh Nhẫn giả đối đầu với đội quân Zetsu trắng trong đại chiến, nhằm bảo vệ thế giới ninja khỏi kế hoạch Tsukuyomi Vĩnh cửu.', 350000),
('Đại chiến ninja 2', 420, 'naruto&bee_vs_tobi', 'Naruto và Killer Bee hợp lực chiến đấu với Obito cùng các Vĩ Thú bị điều khiển, nỗ lực ngăn chặn kế hoạch hồi sinh Thập Vĩ.', 400000),
('Đại chiến ninja 3', 440, 'naruto&sasuke_vs_madara', 'Naruto và Sasuke phối hợp đối đầu Madara trong trận chiến đỉnh cao, nhưng thất bại khi hắn trở thành Jinchuuriki Thập Vĩ và bị Black Zetsu phản bội.', 450000),
('Thu phục vĩ thú 1', 500, '1vi', 'kiêu chiến nhất vĩ', 500000),
('Thu phục vĩ thú 2', 520, '2vi', 'kiêu chiến nhị vĩ', 550000),
('Thu phục vĩ thú 3', 540, '3vi', 'kiêu chiến tam vĩ', 600000),
('Thu phục vĩ thú 4', 560, '4vi', 'kiêu chiến tứ vĩ', 650000),
('Thu phục vĩ thú 5', 580, '5vi', 'kiêu chiến ngũ vĩ', 700000),
('Thu phục vĩ thú 6', 600, '6vi', 'kiêu chiến lục vĩ', 750000),
('Thu phục vĩ thú 7', 620, '7vi', 'kiêu chiến thất vĩ', 800000),
('Thu phục vĩ thú 8', 640, '8vi', 'kiêu chiến bát vĩ', 850000),
('Thu phục vĩ thú 9', 660, '9vi', 'kiêu chiến cửu vĩ', 900000);