CREATE TABLE guild_language_settings (
  guild_id BIGINT NOT NULL,
  language_code VARCHAR(10) NOT NULL DEFAULT 'vi',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (guild_id)
);
