SKILL_MAP = {
    "ino": "Đọc suy nghĩ của kẻ địch, tăng tối đa 70% né tránh skill cho tuyến đầu trong 2 turn.",
    "tenten": "Bậc thầy vũ khí, tấn công toàn bộ kẻ địch, gây 200% sát thương cơ bản.",
    "kankuro": "Điều khiển rối tấn công toàn bộ kẻ địch, gây sát thương cơ bản và hiệu ứng độc trong 1 turn bằng 100% sát thương cơ bản lên tất cả kẻ địch.",
    "shino": "điều khiển bọ kí sinh hút chakra của kẻ địch có nhiều chakra nhất bằng 30% sát thương cơ bản và truyền cho đồng minh có chakra nhiều nhất.",
    "sakura": "nhẫn thuật trị thương hồi máu cho đồng minh thấp máu nhất bằng 500% sát thương cơ bản và buff giáp 50% trong 3 turn.",
    "hinata": "Bát Quái Trận Tăng giáp bản thân bằng 100% sát thương cơ bản trong 3 turn.",
    "temari": "Dùng quạt tạo phong thuật, gây 500% sát thương cơ bản lên tuyến đầu và phá 30% giáp trong 2 turn.",
    "kiba": "Gọi chó tấn công toàn bộ kẻ địch, gây 300% sát thương chuẩn.",
    "choji": "Uống thuốc tăng kích thước, hồi 50% máu đã mất và xóa toàn bộ hiệu ứng bất lợi trên bản thân.",
    "iruka": "Tấn công 2 kẻ địch đầu tiên, gây 300% sát thương.",
    "zabuza": "Tạo sương mù che mắt kẻ địch, tăng 20% né tránh cho toàn đội trong 2 turn.",
    "konohamaru": "Dùng thuật quyến rũ, mê hoặc toàn bộ kẻ địch trong 1 turn.",
    "neji": "Bạch Nhãn Tăng giáp bản thân bằng 100% sát thương cơ bản trong 3 turn và hồi lại 20% máu đã mất.",
    "shikamaru": "Dùng bóng trói toàn bộ kẻ địch trong 2 turn (bản thân Shikamaru cũng không thể hành động trong thời gian này).",
    "rin": "Hồi máu cho 2 đồng minh thấp máu nhất bằng 500% sát thương cơ bản.",
    "yagura": "jinchuriki tam vĩ Tăng giáp bằng 50% sát thương cơ bản và tăng 30% né tránh trong 4 turn.",
    "lee": "Mở cổng chakra, hy sinh 20% máu hiện tại để tăng toàn bộ chỉ số 200% có cộng dồn (max 3500 damage, 600 giáp).",
    "kurenai": "Dùng ảo thuật khiến tuyến đầu của đối phương tự tấn công đồng minh trong 2 turn.",
    "asuma": "Dùng phong thuật tấn công toàn bộ kẻ địch bằng 300% sát thương chuẩn, phá giáp vĩnh viễn 5% và kết liễu kẻ địch nếu dưới 5% máu tối đa.",
    "hidan": "Nguyền rủa cả team địch, phản lại 70% sát thương nhận vào trong 3 turn.",
    "kimimaro": "Hồi máu bằng 400% sát thương cơ bản và phản lại 40% sát thương trong 2 turn.",
    "sasori": "Điều khiển rối Tấn công tuyến đầu, giảm 50% giáp và gây độc bằng 200% sát thương cơ bản trong 3 turn.",
    "sai": "Dùng bút vẽ hổ, hổ vồ toàn đội địch bằng 300% sát thương cơ bản, kết liễu ngay lập tức nếu máu dưới 5% tối đa.",
    "kabuto": "Dùng Uế Thổ Chuyển Sinh, hồi sinh 1 đồng minh đã chết với 50% máu tối đa. Nếu không có ai chết, hồi máu cho cả team bằng 200% sát thương cơ bản.",
    "yamato": "Dùng Mộc Độn trói chân tuyến đầu địch, gây 300% sát thương cơ bản và khóa skill trong 2 turn.",
    "deidara": "Tạo vụ nổ lớn, gây 500% sát thương chuẩn lên tuyến đầu.",
    "gaara": "Tạo lớp cát phòng thủ tuyệt đối, tăng giáp cho toàn đội bằng 100% sát thương cơ bản trong 5 turn.",
    "chuninkakashi": "Dùng Lôi Độn Chidori cực mạnh lên tuyến đầu, gây 400% sát thương cơ bản và lan sang mục tiêu thứ hai với 50% sát thương.",
    "kakuzu": "Sở hữu 4 trái tim, hồi máu bằng 500% sát thương cơ bản và tăng giáp 100% trong 4 turn.",
    "kushina": "Thuật phong ấn cực mạnh, khóa chakra toàn bộ địch trong 3 turn và gây 300% sát thương cơ bản lên toàn đội.",
    "konan": "Gây sát thương cực mạnh lên 2 kẻ địch tuyến sau bằng 500% sát thương cơ bản.",
    "kisame": "Dùng Thủy Ngục, giam cầm tuyến đầu địch trong 3 turn, tăng giáp bản thân 200% trong 5 turn.",
    "obito": "Tăng 100% tỉ lệ chí mạng và 200% sát thương cơ bản của bản thân trong 6 turn.",
    "gengetsu": "Dùng Thủy Độn xuyên giáp tuyến đầu, gây 300% sát thương chuẩn và giảm 50% giáp đối phương trong 2 turn.",
    "bee": "Bắn Bom Vĩ Thú vào toàn đội địch, gây 200% sát thương cơ bản và choáng trong 1 turn.",
    "raikage": "Tăng né tránh lên 70% trong 4 turn, tấn công kẻ địch đầu tiên với 500% sát thương chuẩn.",
    "itachi": "Dùng ảo thuật khiến 2 kẻ địch hàng đầu tự tấn công đồng minh trong 2 turn, gây 200% sát thương cơ bản.",
    "pain": "Thần La Thiên Trinh, gây 500% sát thương cơ bản lên toàn đội địch và giảm tốc 100% trong 3 turn.",
    "sasuke": "Dùng Amaterasu thiêu đốt 2 kẻ địch tuyến sau bằng 100% sát thương cơ bản trong 4 turn.",
    "9naruto": "Dạng Vĩ Thú điên cuồng, tăng 200% sát thương bản thân trong 3 turn, tấn công toàn bộ địch bằng 200% sát thương cơ bản.",
    "hokagekakashi": "Sao chép tất cả buff của địch áp dụng lên bản thân và tấn công toàn đội địch bằng 400% sát thương cơ bản.",
    "guy": "Hi sinh 10% máu hiện tại để tăng toàn bộ chỉ số bản thân lên 250% có cộng dồn (max 5000 damage, 800 giáp).",
    "nagato": "Hồi sinh 1 đồng minh đã chết với 100% máu nhưng giảm một nửa toàn bộ chỉ số. Nếu không có ai chết, hồi máu cho đồng minh thấp máu nhất bằng 400% sát thương cơ bản.",
    "onoki": "Dùng Trần Độn, gây 200% sát thương cơ bản và giảm một nửa toàn bộ chỉ số của tất cả địch trong 2 turn.",
    "mei": "Dùng Dung Nham nóng thiêu đốt toàn bộ địch bằng 200% sát thương cơ bản trong 3 turn.",
    "tsunade": "Triệu hồi Sên Thần, hồi máu bằng 700% sát thương cơ bản và buff giáp 30% trong 5 turn.",
    "orochimaru": "Dược sĩ điên, tự hồi phục mỗi turn bằng 300% sát thương cơ bản trong 5 turn.",
    "jiraiya": "Hỏa độn Gây 500% sát thương chuẩn lên toàn bộ địch.",
    "minato": "Tăng né tránh bản thân lên 70% trong 3 turn, gây 500% sát thương toàn đội địch và kết liễu nếu dưới 20% máu tối đa.",
    "hiruzen": "Dùng Thuật Phong Ấn, gây sát thương tuyến đầu bằng 30% máu tối đa của mục tiêu + 200% sát thương cơ bản. Kết liễu ngay nếu đối phương dưới 10% máu (sát thương chuẩn max 2500 damage chuẩn).",
    "tobirama": "Dùng cấm thuật gây 400% sát thương cơ bản lên toàn đội địch, giải toàn bộ debuff và miễn nhiễm sát thương trong 3 turn.",
    "madara": "Dùng Susanoo đập mạnh, gây 400% sát thương chuẩn và choáng toàn đội địch trong 2 turn.",
    "hashirama": "Phật nghìn tay Hồi máu cho toàn đội bằng 500% sát thương cơ bản và buff miễn nhiễm sát thương trong 2 turn, giải mọi loại hiệu ứng bất lợi cho tất cả đồng minh",
    "danzo": "Dùng Sharingan gây 300% sát thương cơ bản lên toàn đội địch và khiến chúng bị câm lặng trong 2 turn.",
    "haku": "Dùng Băng Thuật, buff phản damage 70% cho toàn bộ đồng minh trong 2 turn.",
    "kakashi": "Dùng Chidori cực mạnh gây 500% sát thương chuẩn lên toàn bộ địch và phá 80% giáp trong 2 turn.",
    "naruto": "Kết hợp Rasenshuriken và Bom Vĩ Thú, gây 400% sát thương cơ bản lên toàn đội địch và làm kẻ địch mất 40 charka, nếu Naruto đang ở trạng thái máu yếu skill sẽ gây 1000% damage.",
    "susanoosasuke": "Dùng Susanoo bắn cung tên, gây 800% sát thương cơ bản lên mục tiêu đầu tiên và choáng 2 turn.",
    "6pain": "Dùng Thần La Thiên Trinh cực mạnh, gây 500% sát thương cơ bản lên toàn bộ địch, kết liễu ngay nếu địch dưới 25% máu và choáng 1 turn.",
    "akatsukiitachi": "Dùng ảo thuật cực mạnh, khiến kẻ địch tự đánh nhau trong 2 turn."
}
